/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const OrdersIndexLazyImport = createFileRoute('/orders/')()
const CartIndexLazyImport = createFileRoute('/cart/')()
const ProductsIdIndexLazyImport = createFileRoute('/products/$id/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const OrdersIndexLazyRoute = OrdersIndexLazyImport.update({
  path: '/orders/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/orders/index.lazy').then((d) => d.Route))

const CartIndexLazyRoute = CartIndexLazyImport.update({
  path: '/cart/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cart/index.lazy').then((d) => d.Route))

const ProductsIdIndexLazyRoute = ProductsIdIndexLazyImport.update({
  path: '/products/$id/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/products/$id/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cart/': {
      preLoaderRoute: typeof CartIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/orders/': {
      preLoaderRoute: typeof OrdersIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/products/$id/': {
      preLoaderRoute: typeof ProductsIdIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  CartIndexLazyRoute,
  OrdersIndexLazyRoute,
  ProductsIdIndexLazyRoute,
])

/* prettier-ignore-end */
